apiVersion: composition.krateo.io/v0-1-0
kind: Nginxwebserver
metadata:
  name: nginxwebserver-composition-1
  namespace: krateo-system
spec:
  # override values.yaml of the chart here
  service:
    type: NodePort
